### ISSUE TITLE
Defmt should not block when a debugger is not attached

### ISSUE THREAD

**Issue by jamesmunns** [knurling-rs/probe-run#68] opened 2020-09-21 12:56 UTC
We should not block CPU execution if there is no debugger attached.

We could make this nonblocking, but we would need to make the defmt line protocol robust enough to handle dropped bytes in the stream.

**Comment by jamesmunns** [comment] 2020-09-21 13:01
Related: https://github.com/knurling-rs/defmt/issues/133

**Comment by jonas-schievink** [comment] 2020-09-21 13:03
Duplicate of https://github.com/knurling-rs/defmt/issues/133

**Closed by jonas-schievink** 2020-09-21 13:03 UTC
